export const SET_LOCOMOTIVE_FIELD = "SET_LOCOMOTIVE_FIELD";
export const SET_PLAYER_HAND = "SET_PLAYER_HAND";
export const SET_BUILD_CONNECTION_IDS = "SET_BUILD_CONNECTION_IDS";
export const PREPARE_NEXT_ROUND_SUCCESS = "PREPARE_NEXT_ROUND_SUCCESS";
