export const SET_LOCOMOTIVE_FIELD = "SET_LOCOMOTIVE_FIELD";
export const SET_PLAYER_HAND = "SET_PLAYER_HAND";
export const SET_BUILD_CONNECTION_IDS = "SET_BUILD_CONNECTION_IDS";
export const PREPARE_NEXT_ROUND_SUCCESS = "PREPARE_NEXT_ROUND_SUCCESS";
export const BUILD_SUCCESS = "BUILD_SUCCESS";
export const SYNC_STATE = "SYNC_STATE";
export const SELECT_CARD_FOR_BUILDING_SUCCESS =
  "SELECT_CARD_FOR_BUILDING_SUCCESS";
export const INIT_GAME_SUCCESS = "INIT_GAME_SUCCESS";
export const UNSELECT_CARD_SUCCESS = "UNSELECT_CARD_SUCCESS";
export const CARD_DRAW_FROM_FIELD_SUCCESS = "CARD_DRAW_FROM_FIELD_SUCCESS";
export const JOIN_SUCCESS = "JOIN_SUCCESS";
